"""Step 2: data-flow validation on one BH (GRO J1655-40) and one NS (4U 1636-53) StdProd spectrum.
Writes figures/step2_two_sources.png and reports/step2_fits_check.md. Not a classification test."""
from common import *
from config import *
from spectra import *
from plotstyle import *
import numpy as np

PAIRS = [('91702-01-66-05', 'GRO J1655-40', 'BH'), ('91024-01-82-00', '4U 1636-53', 'NS')]
lines = ['# Step 2 FITS check (auto-generated by scripts/05_two_source_check.py)', '']
fig, axes = plt.subplots(2, 2, figsize=(10, 6.5), sharex=True, gridspec_kw=dict(height_ratios=[3, 1.3]))
for j, (obs, name, lab) in enumerate(PAIRS):
    p = ROOT/f'data/raw/spectra/{obs}/xp{obs.replace("-", "")}'
    s, b, r = read_pha(str(p)+'_s2.pha.gz'), read_pha(str(p)+'_b2.pha.gz'), read_rsp(str(p)+'.rsp.gz')
    dtf = s['counts'].sum()/s['exposure']/s['npcu']*1e-5
    net, err, rs, es, rb, eb = net_spectrum(s, b, 1/(1-dtf))
    w = r['ch_hi'] - r['ch_lo']; e = np.sqrt(r['ch_lo']*r['ch_hi']); n = s['npcu']
    good = (r['ch_lo'] >= 3) & (r['ch_hi'] <= 45)
    band = (r['ch_lo'] >= 4.9) & (r['ch_hi'] <= 25.4)
    ax = axes[0, j]
    for v, ev, c, lbl in [(rs, es, INK2, 'total (source+bkg)'), (rb, eb, '#9e9d98', 'background model'),
                          (net, err, CLASS_COLOR[lab], 'net (deadtime-corr.)')]:
        pos = good & (v > 0)
        ax.errorbar(e[pos], (v/w/n)[pos], yerr=(ev/w/n)[pos], fmt='o', ms=2.5, lw=0.8, color=c, label=lbl)
    nonpos = good & (net <= 0)
    ax.axvspan(5, 25, color=GRID, alpha=0.5, lw=0)
    ax.set_xscale('log'); ax.set_yscale('log')
    ax.set_title(f'{name} ({lab})  ObsID {obs}\n{s["date_obs"][:10]}, PCUs {s["pcus"]}, exposure {s["exposure"]:.0f} s', loc='left')
    ax.set_xlim(2.8, 48)
    ax.set_ylabel('count s$^{-1}$ keV$^{-1}$ PCU$^{-1}$\n(instrument counts, not flux)')
    if j == 0: ax.legend(loc='lower left')
    ax2 = axes[1, j]
    ratio = net/rb
    ax2.plot(e[good], ratio[good], 'o-', ms=2.5, color=CLASS_COLOR[lab])
    ax2.axhline(1, color=INK2, lw=0.8, ls='--'); ax2.set_yscale('log'); ax2.axvspan(5, 25, color=GRID, alpha=0.5, lw=0)
    ax2.set_ylabel('net / background'); ax2.set_xlabel('channel energy (keV, EBOUNDS)')
    ax2.set_xticks([3, 5, 10, 20, 40]); ax2.set_xticklabels(['3', '5', '10', '20', '40'])
    lines += [f'## {name} ({lab}) ObsID {obs}',
              f'- OBJECT header: {s["object"]}; DATE-OBS {s["date_obs"]}; creator {s["creator"]}',
              f'- Source file: HDUCLAS2/3 = {s["hduclas2"]}/{s["hduclas3"]}, COUNTS unit = {s["unit"]} (raw counts, not rate/flux); '
              f'POISSERR={s["poisserr"]}, SYS_ERR={s["sys_err"]} (no systematic error included), QUALITY={s["quality"]}, GROUPING={s["grouping"]}',
              f'- EXPOSURE src/bkg = {s["exposure"]:.1f}/{b["exposure"]:.1f} s; BACKSCAL src/bkg = {s["backscal"]}/{b["backscal"]}; AREASCAL = {s["areascal"]}',
              f'- Background file class = {b["hduclas2"]}/{b["hduclas3"]} (pcabackest model prediction; STAT_ERR = sqrt(model counts))',
              f'- PCUs summed (ROWIDn) = {s["pcus"]} -> N_PCU={n}; response DETNAM={r["detnam"]}, matrix {r["R"].shape}, '
              f'effective area at 6 keV ~ {r["R"][np.argmin(abs(r["e_lo"]-6))].sum():.0f} cm^2 (~{r["R"][np.argmin(abs(r["e_lo"]-6))].sum()/n:.0f}/PCU)',
              f'- Channel binning CPIX1 = {s["cpix"]}; channels with 4.9<=E<=25.4 keV: {band.sum()} '
              f'({r["ch_lo"][band][0]:.2f}-{r["ch_hi"][band][-1]:.2f} keV)',
              f'- Estimated good-xenon deadtime fraction per PCU = {dtf:.4f} (lower bound: VLE/propane/coincident rates need Standard-1)',
              f'- Net 5-25 keV = {np.sum(net[band])/n:.1f} count/s/PCU; background 5-25 keV = {np.sum(rb[band])/n:.2f} count/s/PCU; '
              f'non-positive net channels in band: {int(np.sum(net[band] <= 0))}', '']
fig.suptitle('Step 2: RXTE/PCA Standard-2 StdProd spectra (count space, response NOT unfolded); grey band = 5-25 keV analysis range',
             x=0.01, ha='left', fontsize=10)
fig.savefig(ROOT/'figures/step2_two_sources.png')
(ROOT/'reports/step2_fits_check.md').write_text('\n'.join(lines), encoding='utf-8')
print('\n'.join(lines))
progress('2_two_source_check', 'figures/step2_two_sources.png and reports/step2_fits_check.md written')
