"""Step 5: error analysis; A (intensity) vs B (shape) comparison. Uses LOSO out-of-fold predictions only."""
from common import *
from config import *
from plotstyle import *
import numpy as np, pandas as pd
from scipy.stats import spearmanr

oof = pd.read_csv(ROOT/'results/oof_predictions_loso.csv', dtype={'obs_id': str})
obs = pd.read_csv(ROOT/'data/observations.csv', dtype={'obs_id': str})
src = pd.read_csv(ROOT/'data/sources.csv'); order = list(src.source_id); lab = dict(zip(src.source_id, src.label))
meta = obs[obs.in_dataset][['obs_id', 'mjd', 'exposure_s', 'npcu', 'pcus', 'net_rate_5_25', 'net_snr', 'bkg_fraction',
                            'hardness_10_25_over_5_10', 'dtf_xe', 'n_nonpositive_bins']]
d = oof.merge(meta, on='obs_id', how='left', validate='many_to_one')
assert d.mjd.notna().all()
d['correct'] = d.true_label == d.predicted_label
L = ['# Step 5 error analysis (auto-generated by scripts/08_error_analysis.py)', '',
     'All numbers are LOSO out-of-fold. Observations of the same source are NOT independent; '
     'the effective sample size for "generalisation to new objects" is 8 sources.', '']

# 1. per-source accuracy table: A vs B
ps = pd.read_csv(ROOT/'results/per_source_results.csv')
tab = ps[ps.model != 'Dummy'].pivot_table(index='source_id', columns=['model', 'representation'], values='obs_accuracy').reindex(order)
L += ['## Per-source observation accuracy (LOSO)', '', tab.round(2).to_string(), '']
tab2 = ps[ps.model != 'Dummy'].pivot_table(index='source_id', columns=['model', 'representation'], values='mean_BH_score').reindex(order)
L += ['## Per-source mean BH score (source-level rule: >= 0.5 -> BH)', '', tab2.round(2).to_string(), '']

# 2. dominance: leave-one-source-out of the *metric* (how much mean per-source accuracy depends on one source)
L += ['## Sensitivity of mean per-source accuracy to any single source', '']
for (rep, m), t in ps[ps.model != 'Dummy'].groupby(['representation', 'model']):
    acc = t.set_index('source_id').obs_accuracy
    drops = {s: acc.drop(s).mean() for s in acc.index}
    L.append(f'- {rep}/{m}: mean {acc.mean():.2f}; range when dropping one source {min(drops.values()):.2f}-{max(drops.values()):.2f}; '
             f'sources with accuracy <0.5: {", ".join(acc.index[acc < .5]) or "none"}')
L.append('')

# 3. errors vs observation covariates (medians correct vs wrong, and Spearman of BH_score with covariate within class)
cov = ['net_snr', 'exposure_s', 'bkg_fraction', 'net_rate_5_25', 'hardness_10_25_over_5_10', 'npcu', 'dtf_xe']
L += ['## Covariates of misclassification (median correct | median wrong; n wrong)', '',
      '(descriptive only; not significance tests, because observations are clustered within sources)', '']
for (rep, m), t in d[d.model != 'Dummy'].groupby(['representation', 'model']):
    parts = []
    for c in cov:
        a, b = t[t.correct][c], t[~t.correct][c]
        parts.append(f'{c}: {a.median():.3g} | {b.median():.3g}' if len(b) else f'{c}: {a.median():.3g} | -')
    L.append(f'- {rep}/{m} (n wrong={int((~t.correct).sum())}): ' + '; '.join(parts))
L += ['', '## Within-class Spearman rho between BH score and covariates (clustered data: descriptive)', '']
for (rep, m), t in d[d.model != 'Dummy'].groupby(['representation', 'model']):
    for cls in ['BH', 'NS']:
        tt = t[t.true_label == cls]
        L.append(f'- {rep}/{m} true {cls}: ' + '; '.join(f'{c} {spearmanr(tt.BH_score, tt[c]).statistic:+.2f}'
                                                       for c in ['net_rate_5_25', 'hardness_10_25_over_5_10', 'net_snr', 'npcu']))
L.append('')
# 4. A vs B agreement per observation
for m in ['LogReg', 'RandomForest']:
    p = d[d.model == m].pivot_table(index='obs_id', columns='representation', values='correct', aggfunc='first')
    L.append(f'- {m}: both correct {int((p.A_intensity & p.B_shape).sum())}, only A {int((p.A_intensity & ~p.B_shape).sum())}, '
             f'only B {int((~p.A_intensity & p.B_shape).sum())}, both wrong {int((~p.A_intensity & ~p.B_shape).sum())} (of {len(p)})')
L += ['', '## State labels', '',
      'No verified per-ObsID spectral-state labels were compiled for this sample; therefore no state-resolved analysis is reported. '
      'The (10-25)/(5-10) keV count ratio below is an instrument-space hardness diagnostic, not a state label.', '']
(ROOT/'results/error_analysis.md').write_text('\n'.join(L), encoding='utf-8')
print('\n'.join(L))

# ---- figures ----
for m in ['LogReg', 'RandomForest']:
    fig, ax = plt.subplots(1, 2, figsize=(12, 4.6), sharex=True, sharey=True)
    for a, rep in zip(ax, ['A_intensity', 'B_shape']):
        t = d[(d.model == m) & (d.representation == rep)]
        for cls, mk in [('BH', 'o'), ('NS', 's')]:
            for ok in [True, False]:
                u = t[(t.true_label == cls) & (t.correct == ok)]
                a.scatter(u.hardness_10_25_over_5_10, u.net_rate_5_25, marker=mk, s=26 if ok else 40,
                          facecolor=CLASS_COLOR[cls] if ok else 'none', edgecolor=CLASS_COLOR[cls], lw=1.2,
                          label=f'true {cls}, {"correct" if ok else "WRONG"}')
        a.set_xscale('log'); a.set_yscale('log'); a.set_title(f'{m} / {rep}', loc='left')
        a.set_xlabel('count ratio (10-25 keV)/(5-10 keV)  [instrument space]')
    ax[0].set_ylabel('net count rate 5-25 keV (count/s/PCU)'); ax[1].legend(loc='lower right', fontsize=7)
    fig.suptitle('Hardness-intensity (count space); hollow = misclassified in LOSO', x=0.01, ha='left')
    fig.savefig(ROOT/f'figures/step5_hid_errors_{m}.png'); plt.close(fig)

fig, ax = plt.subplots(1, 2, figsize=(12, 4.2), sharey=True)
for a, m in zip(ax, ['LogReg', 'RandomForest']):
    t = ps[ps.model == m].pivot(index='source_id', columns='representation', values='obs_accuracy').reindex(order)
    yy = np.arange(len(order))
    a.barh(yy-0.2, t.A_intensity, 0.38, color='#2a78d6', label='A: intensity kept')
    a.barh(yy+0.2, t.B_shape, 0.38, color='#1baf7a', label='B: shape only')
    a.axvline(0.5, color=INK2, ls='--', lw=.8); a.set_xlim(0, 1); a.set_title(m, loc='left')
    a.set_yticks(yy); a.set_yticklabels([f'{s} ({lab[s]})' for s in order]); a.set_xlabel('fraction of held-out observations correct')
ax[0].invert_yaxis(); ax[1].legend(loc='lower right')
fig.suptitle('Per-source LOSO accuracy: intensity-kept (A) vs shape-only (B)', x=0.01, ha='left')
fig.savefig(ROOT/'figures/step5_per_source_A_vs_B.png'); plt.close(fig)

fig, ax = plt.subplots(1, 2, figsize=(12, 4), sharey=True)
for a, rep in zip(ax, ['A_intensity', 'B_shape']):
    t = d[(d.model == 'RandomForest') & (d.representation == rep)]
    for s in order:
        u = t[t.source_id == s]
        a.scatter(u.net_rate_5_25, u.BH_score, s=18, color=CLASS_COLOR[lab[s]], alpha=.7, lw=0)
    a.axhline(.5, color=INK2, ls='--', lw=.8); a.set_xscale('log'); a.set_title(f'RandomForest / {rep}', loc='left')
    a.set_xlabel('net count rate 5-25 keV (count/s/PCU)')
ax[0].set_ylabel('LOSO BH score')
fig.suptitle('Does the score track brightness? (blue = true BH, orange = true NS)', x=0.01, ha='left')
fig.savefig(ROOT/'figures/step5_score_vs_rate.png'); plt.close(fig)
progress('5_error_analysis', 'results/error_analysis.md + step5 figures')
